### PR TITLE
Specify a directory for the hardware defintition

### PR DESCRIPTION
**Pull request by tssva**
Not all hardware definition repositories store the board files under the hardware directory. This PR allows specifying the directory in the repo which contains the files.

### CODE REVIEW

**Comment by mmone** [comment]
Hi Tim,

i'n not sure about whether this is a good solution. With all those additional options things get more and more complicated and break easily. I would need to test it, but can't this problem be addressed with the board string. Eg. using "hardware:anet:avr:anet" If I remember correctly this basically mirrors the directory structure. Can't test it at the moment though.

**Comment by tssva** [comment]
I don't like changing the board string because it is passed on to the Arduino app, so doing so would now mean having to massage it back into the correct format.

I attempted to mirror the same format that was already in use for the libraries, but I could also change this to use a separate variable to define the path in the repository for the board files. If the variable is empty, as it would be by default, than the behavior remains the same as today.

**Comment by mmone** [comment]
I think the variable solution is more transparent. I like it.

**Comment by mmone** [comment]
Hi @tssva are you planing to update this PR with the variable solution?

**Comment by tssva** [comment]
Yes, I have made the changes but need to push it. Life got in the way. Will push it tonight or tomorrow.

**Comment by mmone** [comment]
Sure no rush.

**Comment by tssva** [comment]
Updated the patch to use a separate variable for the directory.

**Pull request closed without merging**
